# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # or whatever you already use
    hooks:
      - id: mypy
        args:
          - --install-types
          - --non-interactive
        additional_dependencies:
          - types-requests
          - types-urllib3
          # (optional, but keeps versions recent)
          - huggingface-hub>=0.25

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--config", ".flake8"]
